/* Structure for the `balance` table : */

CREATE TABLE `balance` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `concept` VARCHAR(45) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `january` DECIMAL(10,2) DEFAULT NULL,
  `february` DECIMAL(10,2) DEFAULT NULL,
  `march` DECIMAL(10,2) DEFAULT NULL,
  `april` DECIMAL(10,2) DEFAULT NULL,
  `may` DECIMAL(10,2) DEFAULT NULL,
  `june` DECIMAL(10,2) DEFAULT NULL,
  `july` DECIMAL(10,2) DEFAULT NULL,
  `august` DECIMAL(10,2) DEFAULT NULL,
  `september` DECIMAL(10,2) DEFAULT NULL,
  `october` DECIMAL(10,2) DEFAULT NULL,
  `november` DECIMAL(10,2) DEFAULT NULL,
  `december` DECIMAL(10,2) DEFAULT NULL,
  `year` INTEGER DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`)
) ENGINE=InnoDB
AUTO_INCREMENT=11 ROW_FORMAT=DYNAMIC CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci';