CREATE TABLE `bills` (
  `id` int NOT NULL AUTO_INCREMENT,
  `typeofexpenseid` int DEFAULT NULL,
  `summary` varchar(200) DEFAULT NULL,
  `january` decimal(10,2) DEFAULT NULL,
  `february` decimal(10,2) DEFAULT NULL,
  `march` decimal(10,2) DEFAULT NULL,
  `april` decimal(10,2) DEFAULT NULL,
  `may` decimal(10,2) DEFAULT NULL,
  `june` decimal(10,2) DEFAULT NULL,
  `july` decimal(10,2) DEFAULT NULL,
  `august` decimal(10,2) DEFAULT NULL,
  `september` decimal(10,2) DEFAULT NULL,
  `october` decimal(10,2) DEFAULT NULL,
  `november` decimal(10,2) DEFAULT NULL,
  `december` decimal(10,2) DEFAULT NULL,
  `wallet` int DEFAULT NULL,
  `verified` tinyint(1) DEFAULT NULL,
  `reserved` tinyint(1) DEFAULT NULL,
  `paid` tinyint(1) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `observations` varchar(255) DEFAULT NULL,
  `resourcepayment` varchar(45) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fx_typeofexpenseid_typeofexpense_idx` (`typeofexpenseid`),
  KEY `fx_wallet_entities_idx` (`wallet`),
  CONSTRAINT `fx_typeofexpenseid_typeofexpense` FOREIGN KEY (`typeofexpenseid`) REFERENCES `typeofexpense` (`id`),
  CONSTRAINT `fx_wallet_entities` FOREIGN KEY (`wallet`) REFERENCES `entities` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=116 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci