/* Structure for the `status` table : */

CREATE TABLE `status` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `entityname` VARCHAR(45) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `order` INTEGER DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`)
) ENGINE=InnoDB
AUTO_INCREMENT=7 ROW_FORMAT=DYNAMIC CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci';

/* Data for the `status` table  (LIMIT 0,500) */

INSERT INTO `status` (`id`, `name`, `entityname`, `order`) VALUES
  (1,'PENDIENTE','ORDERS|ORDERDETAILS',1),
  (2,'PEDIDO','ORDERS|ORDERDETAILS',2),
  (3,'PAGADO','ORDERS|ORDERDETAILS',3),
  (4,'RECIBIDO','ORDERS|ORDERDETAILS',4),
  (5,'CANCELADO','ORDERS|ORDERDETAILS',5),
  (6,'NO RECIBIDO','ORDERS|ORDERDETAILS',6);
COMMIT;

