/* Structure for the `typeofexpense` table : */

CREATE TABLE `typeofexpense` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `categoriesid` INTEGER DEFAULT NULL,
  `referentid` INTEGER DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  KEY `fx_typeofexpense_categoriesid_idx` USING BTREE (`categoriesid`),
  CONSTRAINT `fx_typeofexpense_categoriesid` FOREIGN KEY (`categoriesid`) REFERENCES `categories` (`id`)
) ENGINE=InnoDB
AUTO_INCREMENT=36 ROW_FORMAT=DYNAMIC CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci';

/* Data for the `typeofexpense` table  (LIMIT 0,500) */

INSERT INTO `typeofexpense` (`id`, `type`, `categoriesid`, `referentid`) VALUES
  (1,'CUOTA ALIMENTARIA',1,NULL),
  (2,'ALQUILER',1,NULL),
  (3,'MEDICAMENTOS',1,NULL),
  (4,'GASTOS GENERALES HOGAR',1,NULL),
  (5,'UTILES ESCOLARES',4,NULL),
  (6,'SALIDAS C/HIJOS',4,NULL),
  (7,'CARGA DE CELULARES',2,NULL),
  (8,'ACTIVIDADES PERSONALES',2,NULL),
  (9,'RESUMEN TC BCO RIO AMEX',1,2),
  (10,'RESUMEN TC BCO RIO VISA',1,1),
  (11,'RESUMEN TC NX VISA VIRTUAL',1,5),
  (12,'RESUMEN TC NX VISA',1,3),
  (13,'RESUMEN TC NX MASTER CARD',1,4),
  (14,'RESUMEN MP CREDITO',1,6),
  (15,'VIATICOS HIJOS',4,NULL),
  (16,'GIMNASIO',7,NULL),
  (17,'AYUDA ESPIRITUAL',9,NULL),
  (18,'ELECTRODOMESTICOS',2,NULL),
  (19,'EDUCACION Y FORMACION',3,NULL),
  (20,'INVERSIONES',5,NULL),
  (21,'ABOGADAS',6,NULL),
  (22,'PSICOLOGA',7,NULL),
  (23,'MASOTERAPIA',7,NULL),
  (24,'SEGUROS DE VIDA',9,NULL),
  (25,'SEGUROS ROBO CAJERO',9,NULL),
  (26,'PERSONAL 4G',9,NULL),
  (27,'TELECENTRO WIFI',9,NULL),
  (28,'SERVICIOS AMOC',9,NULL),
  (29,'MICROSOFT 365',9,NULL),
  (30,'SPOTIFY FAMILIAR',9,NULL),
  (31,'YOUTUBE PREMIUN',9,NULL),
  (32,'LINKEDIN',9,NULL),
  (33,'MERCADO LIBRE DEBITO',1,NULL),
  (34,'COSMETICOS AVON',2,NULL),
  (35,'EDENOR (LUZ)',1,NULL),
  (36,'PRESTAMOS NX',8,NULL);
COMMIT;

